### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by mhils** [dust8/amfpy#1]
Hi @dust8,

We were just looking for a Python 3 replacement for pyamf for @mitmproxy and stumbled upon your project, which would probably be a good fit for our needs. :smiley:
Could you clarify what license this code is under? Is this something that would be compatible with our MIT license?

Thanks!
Max

**Comment by dust8** [comment]
I've added the mit license. The project is not completed, and has stopped development. It can only parse amf0 protocol, no more features, you need to do more work.

**Comment by mhils** [comment]
Thanks! We are aware of the limitations - I'll let you know if we build something on top :smiley:
